services:
  tipptrace:
    build: .
    container_name: tipptrace
    ports:
      - "8000:8000"
    environment:
      # SQLite-DB persistent im Volume:
      SQLALCHEMY_DATABASE_URI: "sqlite:////data/app.db"
      # Optional: wird im /healthz-JSON ausgegeben
      APP_VERSION: "1.0.0"
      # Falls du einen anderen Port willst:
      # PORT: "8000"
    volumes:
      - tipptrace_data:/data
    restart: unless-stopped
    # Dockerfile enthält bereits einen HEALTHCHECK -> keine doppelte Definition nötig
    # Wenn du eigenständige Compose-Checks willst, könntest du hier auch einen healthcheck: definieren.

volumes:
  tipptrace_data:
